### ISSUE TITLE
Project plan

### ISSUE THREAD

**Issue by vincentaudebert** [vincentaudebert/test-repo-from-init#8]
- [ ] Use collaborative client, design, content, and development conversations to decide an approach to meeting the goals through features of the site or app.
- [ ] Scope and prioritise features that serve the objectives and the strategy.
- [ ] Identify any research we will need to conduct to deliver effectively on those features.
- [ ] Agree on timeframes and milestones.
- [ ] Identify dependencies — research, content, design and technical — and agree in writing with the client how these are to be managed and the impact of delayed delivery of any of these.
- [ ] Decide the proportion of project effort to be expended on each feature — this should be considered a design constraint. Some features are way more important to the project objectives and strategy than others and apportion design and development effort accordingly.
- [ ] Agree on the approach to balancing time, scope and budget with the client. When the proportion of completed work is tracking behind the proportion of budget consumed, will we negotiate a higher fee, descope, and/or adjust the project timeframe? Get this in writing.
- [ ] Organise a daily standup and establish regular check-ins with the client contact/s.
- [ ] Get written agreement from the client on the project plan
